# Changes here will be overwritten by Copier
_commit: v0.14.1
_src_path: gh:bhklab/bhklab-project-template
author_email: bhklab.farnooshabbasaghababazadeh@gmail.com
author_full_name: Farnoosh Abbas Aghababazadeh
github_username: RibaA
has_additional_authors: false
project_description: Biomarker Discovery in Soft Tissue Sarcoma Using Pharmacogenomics
    Data
project_name: sarc-pgx-biomarker
project_slug: sarc-pgx-biomarker
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
